ARG RUST_VERSION

FROM rust:$RUST_VERSION-alpine AS builder

ARG TIMESTAMP
ARG REVISION

LABEL timestamp=$TIMESTAMP revision=$REVISION

ENV USER=rust

# building ring requires Perl
RUN apk add -q musl-dev perl && rustup target add x86_64-unknown-linux-musl

WORKDIR /home/rust/src
RUN cargo new backend
WORKDIR /home/rust/src/backend

# build dependencies
RUN cargo new --lib info && cargo new initdb && cargo new --lib log && cargo new server

COPY --chown=rust Cargo.lock Cargo.toml ./

COPY --chown=rust info/Cargo.toml info/Cargo.toml
COPY --chown=rust initdb/Cargo.toml initdb/Cargo.toml
COPY --chown=rust log/Cargo.toml log/Cargo.toml
COPY --chown=rust server/Cargo.toml server/Cargo.toml
RUN cargo build --target x86_64-unknown-linux-musl --bin backend --release --locked
