ARG RUST_VERSION

FROM ekidd/rust-musl-builder:$RUST_VERSION AS builder

ARG TIMESTAMP
ENV BUILD_TIMESTAMP=$TIMESTAMP
ARG REVISION
ENV BACKEND_REVISION=$REVISION

ENV CARGO_INCREMENTAL=0
ENV OPENSSL_STATIC=1

ENV USER=rust

WORKDIR /home/rust/src
RUN cargo new backend
WORKDIR /home/rust/src/backend

# build dependencies
RUN cargo new initdb && cargo new server

COPY Cargo.lock Cargo.toml ./

COPY server/Cargo.toml server/Cargo.toml
COPY initdb/Cargo.toml initdb/Cargo.toml
RUN cargo build -p initdb --target x86_64-unknown-linux-musl --release --locked

# build project
COPY initdb ./initdb
RUN cargo build -p initdb --target x86_64-unknown-linux-musl --bin initdb --release --frozen --offline

FROM scratch

ARG TIMESTAMP
ARG REVISION
LABEL timestamp=$TIMESTAMP revision=$REVISION

COPY migrations migrations
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENV SSL_CERT_DIR=/etc/ssl/certs/
COPY --from=builder /home/rust/src/backend/target/x86_64-unknown-linux-musl/release/initdb /usr/app/initdb
USER 1000
CMD ["/usr/app/initdb"]
