ARG BASE_IMAGE

FROM $BASE_IMAGE AS builder

WORKDIR /home/rust/src/backend

COPY --chown=rust info ./info
COPY --chown=rust initdb ./initdb
COPY --chown=rust log ./log

# without the `touch`, the compiler doesn't appear to realize the code has changed
RUN touch info/src/lib.rs && touch log/src/lib.rs && cargo build -p initdb --target x86_64-unknown-linux-musl --bin initdb --release --frozen --offline

FROM scratch

ARG TIMESTAMP
ARG REVISION
LABEL timestamp=$TIMESTAMP revision=$REVISION

COPY migrations migrations
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
ENV SSL_CERT_DIR=/etc/ssl/certs/
COPY --from=builder /home/rust/src/backend/target/x86_64-unknown-linux-musl/release/initdb /usr/app/initdb
USER 1000
CMD ["/usr/app/initdb"]
