ARG BASE_IMAGE
ARG POSTGRES_VERSION

FROM $BASE_IMAGE AS builder

WORKDIR /home/rust/src/backend

COPY --chown=rust info ./info
COPY --chown=rust initdb ./initdb
COPY --chown=rust log ./log

# without the `touch`, the compiler doesn't appear to realize the code has changed
RUN touch info/src/lib.rs && touch log/src/lib.rs && cargo build -p initdb --target x86_64-unknown-linux-musl --bin initdb --release --frozen --offline

FROM postgres:$POSTGRES_VERSION

COPY migrations /usr/app/migrations
COPY --from=builder /home/rust/src/backend/target/x86_64-unknown-linux-musl/release/initdb /usr/app/initdb
COPY tools/entrypoint.sh /usr/local/bin/custom-entrypoint.sh

ARG TIMESTAMP
ARG REVISION
LABEL timestamp=$TIMESTAMP revision=$REVISION

ENTRYPOINT ["/usr/local/bin/custom-entrypoint.sh"]
