"""Initial migration.

Revision ID: a17cb8f73e8e
Revises: 
Create Date: 2020-06-11 19:38:35.215252

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a17cb8f73e8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('label', sa.String(length=''), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('label', sa.String(length=''), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gender',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('label', sa.String(length=''), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recording',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=''), nullable=False),
    sa.Column('category_id', sa.SmallInteger(), nullable=False),
    sa.Column('privacy', sa.Enum('Public', 'Unlisted', name='privacy'), nullable=False),
    sa.Column('age_id', sa.SmallInteger(), nullable=True),
    sa.Column('gender_id', sa.SmallInteger(), nullable=True),
    sa.Column('location', sa.String(length=''), nullable=True),
    sa.Column('occupation', sa.String(length=''), nullable=True),
    sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['age_id'], ['age.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['gender_id'], ['gender.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['recording.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recording')
    op.drop_table('gender')
    op.drop_table('category')
    op.drop_table('age')
    # ### end Alembic commands ###
