DROP TABLE IF EXISTS "recordings" CASCADE;

DROP TABLE IF EXISTS "categories" CASCADE;

DROP TABLE IF EXISTS "genders" CASCADE;

DROP TABLE IF EXISTS "ages" CASCADE;

DROP TABLE IF EXISTS "mime_types" CASCADE;

DROP EXTENSION IF EXISTS "uuid-ossp" CASCADE;
